name: grocery_app
description: A new Flutter application.

publish_to: 'none'

version: 1.1.0+4

environment:
  sdk: ">=2.13.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_svg: ^1.0.3

  flutter_staggered_grid_view: ^0.6.2
  dio: ^4.0.6
#  connectivity_plus: ^2.3.6
  equatable: ^2.0.3
#  internet_connection_checker: any
  get_it: ^7.2.0
  get_storage: ^2.0.3
  get: ^4.6.5
  intl_phone_field: ^3.1.0
  pin_code_fields: ^7.4.0
#  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  expandable: ^5.0.1
  progress_state_button: ^1.0.4
  otp_text_field:
  google_fonts:
  easy_date_timeline: any
  uuid: any
  geolocator: ^9.0.2
  firebase_core: ^2.4.0
  intl: ^0.18.0
  pelaicons:
  badges:
  flutter_location_search: any
  flutter_otp_text_field:
  razorpay_flutter: ^1.3.5
  anim_search_bar:
  shimmer:
  location:
    git:
      url: https://github.com/781flyingdutchman/flutterlocation.git
      ref: V4
      path: packages/location
  google_maps_flutter: ^2.5.3
  geocoding: ^2.1.1
  phonepe_payment_sdk: ^2.0.1
  crypto: ^3.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/f4fish_logo.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/account_icons/
    - assets/fonts/
    - assets/loginScreen/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Regular.ttf
        - asset: assets/fonts/gilroy/Gilroy-SemiBold.ttf
        - asset: assets/fonts/gilroy/Gilroy-Bold.otf